name: mymodels
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - anyio==4.12.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - exceptiongroup==1.3.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.7
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pillow==12.0.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - shellingham==1.5.4
      - sympy==1.14.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/mymodels
